name: Deploy Backend (DSpace) - Branch tst

on:
  workflow_dispatch:
  push:
    branches:
      - tst

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, tst-backend-runner]
    env:
      JAVA_VERSION: '17'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Criar arquivo local.cfg (configuração DSpace)
        run: |
          cat <<EOF > dspace/config/local.cfg
          dspace.dir = /volumes/interacoes/dspaceinstall
          dspace.server.url = https://dspace.tst.interacoes.ltap.ifce.edu.br/server
          dspace.server.ssr.url = https://dspace.tst.interacoes.ltap.ifce.edu.br/server
          dspace.ui.url = https://dspace.tst.interacoes.ltap.ifce.edu.br
          dspace.name = InterAções - SASE/MEC
          dspace.shortname = InterAções
          default.language = pt_BR
          solr.server = http://localhost:8983/solr
          solr.multicorePrefix =
          db.url = jdbc:postgresql://localhost:5432/dspace
          db.driver = org.postgresql.Driver
          db.dialect = org.dspace.util.DSpacePostgreSQLDialect
          db.username = dspace
          db.password = dspace
          db.schema = public
          db.maxconnections = 30
          db.maxwait = 10000
          db.minidle = 0
          db.maxidle = 10
          db.initialsize = 0
          db.maxconnlifetime = -1
          db.removeabandoned = false
          db.removeabandonedtimeout = 300
          logging.server.include-after-request = false
          logging.server.include-client-info = false
          logging.server.include-headers = false
          logging.server.include-payload = false
          logging.server.include-query-string = false
          logging.server.include-stacktrace-for-httpcode = 422
          logging.server.max-payload-length = 10000
          EOF

      - name: Build with Maven
        run: mvn package

      - name: Fresh Install DSpace (ant fresh_install)
        run: |
          cd dspace/target/dspace-installer
          ant fresh_install
          
      - name: Reiniciar DSpace REST (systemd)
        run: sudo systemctl restart dspace-rest
